services:
  actual-smart-sync:
    # Instead of building locally, they just pull your pre-built image
    image: ghcr.io/adambeltz2/actual-smart-sync:latest
    container_name: actual_smart_sync
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - TIMEZONE=America/New_York
